
spring.datasource.url=jdbc:postgresql://localhost:5432/spoticloud_db
spring.datasource.username=postgres
spring.datasource.password=11081488


spring.jpa.hibernate.ddl-auto=update

server.port=8081
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect